In [1]:
import matplotlib.pyplot as plt
import astropy
import os
import pandas as pd
import numpy as np
import xlsxwriter
import matplotlib as mpl
from astropy import io
from astropy.io import fits
from astropy import table
from astropy import wcs

In [2]:
catalogue_file = '/home/verlon/Desktop/Astronomaly/Data/Input/Coadd_0260/0260m062/Catalogue/tractor-0260m062.fits'

In [3]:
image_file_g = '/home/verlon/Desktop/Astronomaly/Data/Input/Coadd_0260/0260m062/Images/g-legacysurvey-0260m062-image.fits.fz'
image_file_r = '/home/verlon/Desktop/Astronomaly/Data/Input/Coadd_0260/0260m062/Images/r-legacysurvey-0260m062-image.fits.fz'
image_file_z = '/home/verlon/Desktop/Astronomaly/Data/Input/Coadd_0260/0260m062/Images/z-legacysurvey-0260m062-image.fits.fz'

In [4]:
catalogue = astropy.table.Table(astropy.io.fits.getdata(catalogue_file))

In [5]:
image_z = astropy.table.Table(astropy.io.fits.getdata(image_file_z))

In [6]:
dataframe = {}
for name in catalogue.colnames:
    data = catalogue[name].tolist()
    dataframe[name] = data

In [7]:
old_catalogue = pd.DataFrame(dataframe)
old_catalogue

release  brickid brickname  objid  brick_primary  brightblob  maskbits  \
0        8000   294523  0260m062      0           True           0         0   
1        8000   294523  0260m062      1          False           0         1   
2        8000   294523  0260m062      2          False           0         1   
3        8000   294523  0260m062      3           True           0         0   
4        8000   294523  0260m062      4          False           0         1   
...       ...      ...       ...    ...            ...         ...       ...   
8555     8000   294523  0260m062   8555          False           0         1   
8556     8000   294523  0260m062   8556          False           0         1   
8557     8000   294523  0260m062   8557          False           0         1   
8558     8000   294523  0260m062   8558          False           0         1   
8559     8000   294523  0260m062   8559           True           0      4096   

      type         ra       dec  ...  shapeexp_e1  shapeexp_e1_ivar  \
0     DEV   25.945412 -6.371716  ...          0.0               0.0   
1     DEV   25.946999 -6.379954  ...          0.0               0.0   
2     PSF   25.947223 -6.375302  ...          0.0               0.0   
3     DEV   25.947719 -6.372837  ...          0.0               0.0   
4     REX   25.945132 -6.377418  ...          0.0               0.0   
...    ...        ...       ...  ...          ...               ...   
8555  REX   26.061850 -6.123305  ...          0.0               0.0   
8556  PSF   25.963370 -6.124377  ...          0.0               0.0   
8557  REX   26.047838 -6.124206  ...          0.0               0.0   
8558  PSF   26.047843 -6.123123  ...          0.0               0.0   
8559  DUP   26.126580 -6.354087  ...          0.0               0.0   

      shapeexp_e2  shapeexp_e2_ivar shapedev_r  shapedev_r_ivar  shapedev_e1  \
0             0.0               0.0   2.006413    225340.296875     0.161191   
1             0.0               0.0   0.738184      1851.672363     0.266367   
2             0.0               0.0   0.000000         0.000000     0.000000   
3             0.0               0.0   0.406632      2378.385010     0.067957   
4             0.0               0.0   0.000000         0.000000     0.000000   
...           ...               ...        ...              ...          ...   
8555          0.0               0.0   0.000000         0.000000     0.000000   
8556          0.0               0.0   0.000000         0.000000     0.000000   
8557          0.0               0.0   0.000000         0.000000     0.000000   
8558          0.0               0.0   0.000000         0.000000     0.000000   
8559          0.0               0.0   0.000000         0.000000     0.000000   

      shapedev_e1_ivar shapedev_e2  shapedev_e2_ivar  
0        663634.250000   -0.000461     395096.156250  
1          1010.740356   -0.150187        705.127625  
2             0.000000    0.000000          0.000000  
3           299.701355   -0.121653        435.634338  
4             0.000000    0.000000          0.000000  
...                ...         ...               ...  
8555          0.000000    0.000000          0.000000  
8556          0.000000    0.000000          0.000000  
8557          0.000000    0.000000          0.000000  
8558          0.000000    0.000000          0.000000  
8559          0.000000    0.000000          0.000000  

[8560 rows x 160 columns]

In [8]:
np.sort(old_catalogue.ra)

array([25.88890409, 25.88960809, 25.88971301, ..., 26.15103669,
       26.15105166, 26.15110804])

In [9]:
np.sort(old_catalogue.dec)

array([-6.38087766, -6.3799537 , -6.3795429 , ..., -6.1215277 ,
       -6.12088554, -6.12085056])

hdul = astropy.io.fits.open(image_file_g)
hdul[0].data
plt.figure(figsize = (12,12))
plt.imshow(hdul[0].data, cmap='hot')

hdul = astropy.io.fits.open(image_file_r)
hdul[0].data
plt.figure(figsize = (12,12))
plt.imshow(hdul[0].data, cmap='hot')

hdul = astropy.io.fits.open(image_file_z)
hdul[0].data
plt.figure(figsize = (12,12))
plt.imshow(hdul[0].data, cmap='hot')

In [10]:
original_image = image_file_z.split(os.path.sep)[-1]
original_image

'z-legacysurvey-0260m062-image.fits.fz'

In [11]:
hdul = astropy.io.fits.open(image_file_z)
hdul

[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x7fee437a2d30>, <astropy.io.fits.hdu.compressed.CompImageHDU object at 0x7fee437b01c0>]

In [12]:
w = astropy.wcs.WCS(hdul[0].header, naxis=2)
w

WCS Keywords

Number of WCS axes: 2
CTYPE : ''  ''  
CRVAL : 0.0  0.0  
CRPIX : 0.0  0.0  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : 1.0  1.0  
NAXIS : 0  0

In [13]:
x, y = w.wcs_world2pix(old_catalogue['ra'], old_catalogue['dec'], 1)

In [14]:
x

array([25.94541155, 25.94699887, 25.94722339, ..., 26.0478378 ,
       26.04784329, 26.12658028])

In [15]:
old_catalogue['ra']

0       25.945412
1       25.946999
2       25.947223
3       25.947719
4       25.945132
          ...    
8555    26.061850
8556    25.963370
8557    26.047838
8558    26.047843
8559    26.126580
Name: ra, Length: 8560, dtype: float64

In [16]:
y

array([-6.37171583, -6.3799537 , -6.37530186, ..., -6.12420619,
       -6.1231233 , -6.35408713])

In [17]:
new_catalogue = pd.DataFrame()
new_catalogue['objid'] = catalogue['objid']
new_catalogue['original_image'] = [original_image] * len(new_catalogue)
new_catalogue['flux_g'] = catalogue['flux_g']
new_catalogue['flux_r'] = catalogue['flux_r']
new_catalogue['flux_z'] = catalogue['flux_z']
new_catalogue['x'] = x
new_catalogue['y'] = y
new_catalogue['ra'] = catalogue['ra']
new_catalogue['dec'] = catalogue['dec']
new_catalogue

objid                         original_image     flux_g     flux_r  \
0         0  z-legacysurvey-0260m062-image.fits.fz  14.647056  47.933273   
1         1  z-legacysurvey-0260m062-image.fits.fz   0.300906   1.058756   
2         2  z-legacysurvey-0260m062-image.fits.fz   0.315161   1.082911   
3         3  z-legacysurvey-0260m062-image.fits.fz   0.167745   0.960380   
4         4  z-legacysurvey-0260m062-image.fits.fz   0.733369   1.121266   
...     ...                                    ...        ...        ...   
8555   8555  z-legacysurvey-0260m062-image.fits.fz   0.158827   0.209918   
8556   8556  z-legacysurvey-0260m062-image.fits.fz   0.063598   0.114165   
8557   8557  z-legacysurvey-0260m062-image.fits.fz   0.102805   0.278738   
8558   8558  z-legacysurvey-0260m062-image.fits.fz   0.137012   0.131219   
8559   8559  z-legacysurvey-0260m062-image.fits.fz   0.000000   0.000000   

          flux_z          x         y         ra       dec  
0     105.962326  25.945412 -6.371716  25.945412 -6.371716  
1       5.895619  25.946999 -6.379954  25.946999 -6.379954  
2       2.710563  25.947223 -6.375302  25.947223 -6.375302  
3       3.497689  25.947719 -6.372837  25.947719 -6.372837  
4       1.421438  25.945132 -6.377418  25.945132 -6.377418  
...          ...        ...       ...        ...       ...  
8555    0.591404  26.061850 -6.123305  26.061850 -6.123305  
8556    0.079041  25.963370 -6.124377  25.963370 -6.124377  
8557    0.390089  26.047838 -6.124206  26.047838 -6.124206  
8558    0.226656  26.047843 -6.123123  26.047843 -6.123123  
8559    0.000000  26.126580 -6.354087  26.126580 -6.354087  

[8560 rows x 9 columns]

In [18]:
def convert_tractor_catalogue(catalogue_file, image_file, image_name=''):
    """
    Converts a tractor fits file to a pandas dataframe to be given
    directly to an ImageDataset object.

    Parameters
    ----------
    catalogue_files : string
        tractor catalogue in fits table format 
    image_file:
        The image corresponding to this catalogue (to extract pixel information
        and naming information)
    """

    catalogue = astropy.table.Table(astropy.io.fits.getdata(catalogue_file))

    dataframe = {}
    for name in catalogue.colnames:
        data = catalogue[name].tolist()
        dataframe[name] = data
    
    old_catalogue = pd.DataFrame(dataframe)
    hdul = astropy.io.fits.open(image_file)

    if len(image_name) == 0:
        original_image = image_file.split(os.path.sep)[-1]
    else:
        original_image = image_name
    
    #w = astropy.wcs.WCS(hdul[0].header, naxis=2)
    #x, y = w.wcs_world2pix(old_catalogue['ra'], old_catalogue['dec'], 1)
    
    new_catalogue = pd.DataFrame()
    new_catalogue['objid'] = old_catalogue['objid']
    new_catalogue['original_image'] = [original_image] * len(new_catalogue)
    new_catalogue['flux_g'] = old_catalogue['flux_g']
    new_catalogue['flux_r'] = old_catalogue['flux_r']
    new_catalogue['flux_z'] = old_catalogue['flux_z']
    new_catalogue['x'] = old_catalogue['bx'].astype('int')
    new_catalogue['y'] = old_catalogue['by'].astype('int')
    new_catalogue['ra'] = old_catalogue['ra']
    new_catalogue['dec'] = old_catalogue['dec']
    
    return new_catalogue

In [19]:
prod = convert_tractor_catalogue(catalogue_file, image_file_z, image_name='')

In [20]:
prod.index

RangeIndex(start=0, stop=8560, step=1)

In [21]:
prod.loc[4982]

objid                                              4982
original_image    z-legacysurvey-0260m062-image.fits.fz
flux_g                                         0.395609
flux_r                                          1.08835
flux_z                                          2.87795
x                                                  2937
y                                                  2020
ra                                              25.9362
dec                                            -6.23392
Name: 4982, dtype: object